@PORTFOLIO_HOST_LOCAL=http://localhost:5031

GET {{PORTFOLIO_HOST_LOCAL}}/api/v1/TechStackDescription
Accept: application/json
###

POST {{PORTFOLIO_HOST_LOCAL}}/api/v1/Auth/login
Content-Type: application/json

{
"key": "admin"
}
