// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio_API.Contexts;

#nullable disable

namespace Portfolio_API.Migrations.ResumeDb
{
    [DbContext(typeof(ResumeDbContext))]
    partial class ResumeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("Portfolio_API.Models.Resume.Experience", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("experience_id");

                    b.Property<string>("CompanyName")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("StartedAt")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("started_at");

                    b.HasKey("ExperienceId");

                    b.HasIndex(new[] { "ExperienceId" }, "IX_experiences_experience_id")
                        .IsUnique();

                    b.ToTable("experiences", (string)null);
                });

            modelBuilder.Entity("Portfolio_API.Models.Resume.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<string>("CoverImg")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cover_img");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Duration")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("duration");

                    b.HasKey("ProjectId");

                    b.HasIndex(new[] { "ProjectId" }, "IX_projects_project_id")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
