// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio_API.DataAccess.Contexts;

#nullable disable

namespace Portfolio_API.DataAccess.Migrations
{
    [DbContext(typeof(JDBContext))]
    [Migration("20260501054605_20260501_exp_projects")]
    partial class _20260501_exp_projects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.Experience", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("experience_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExperienceId"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("role");

                    b.HasKey("ExperienceId")
                        .HasName("PK__experien__EB216AFC5362759B");

                    b.ToTable("experiences", (string)null);
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Contribution")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contribution");

                    b.Property<string>("CoverImg")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cover_img");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("project_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ProjectId")
                        .HasName("PK__projects__BC799E1F26444275");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.TechStackDescription", b =>
                {
                    b.Property<int>("StackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stack_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StackId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("StackName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("stack_name");

                    b.HasKey("StackId")
                        .HasName("PK__tech_sta__A44AF9293BF4000B");

                    b.ToTable("tech_stack_description", (string)null);
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.TechStackSpec", b =>
                {
                    b.Property<int>("SpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("spec_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("ImgSrc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("img_src");

                    b.Property<int>("StackId")
                        .HasColumnType("int")
                        .HasColumnName("stack_id");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tool_name");

                    b.HasKey("SpecId")
                        .HasName("PK__tech_sta__F670C567E44DDEB0");

                    b.HasIndex("StackId");

                    b.ToTable("tech_stack_spec", (string)null);
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.TechStackSpec", b =>
                {
                    b.HasOne("Portfolio_API.DataTypes.Models.Portfolio.TechStackDescription", "Stack")
                        .WithMany("TechStackSpecs")
                        .HasForeignKey("StackId")
                        .IsRequired()
                        .HasConstraintName("FK_stack_spec_description");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.TechStackDescription", b =>
                {
                    b.Navigation("TechStackSpecs");
                });
#pragma warning restore 612, 618
        }
    }
}
