// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio_API.DataAccess.Contexts;

#nullable disable

namespace Portfolio_API.DataAccess.Migrations
{
    [DbContext(typeof(JDBContext))]
    partial class JDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.ExpProject", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<int>("TechstackId")
                        .HasColumnType("int")
                        .HasColumnName("techstack_id");

                    b.Property<int>("ExperiencedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("experienced_at");

                    b.HasKey("ProjectId", "TechstackId", "ExperiencedAt")
                        .HasName("PK_ProjectTechStack");

                    b.HasIndex("ExperiencedAt");

                    b.HasIndex("TechstackId");

                    b.ToTable("exp_projects", (string)null);
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.Experience", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("experience_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExperienceId"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("role");

                    b.HasKey("ExperienceId")
                        .HasName("PK__experien__EB216AFCB14726DD");

                    b.ToTable("experiences", (string)null);
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Contribution")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contribution");

                    b.Property<string>("CoverImg")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cover_img");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("project_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ProjectId")
                        .HasName("PK__projects__BC799E1F2A481118");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.TechStackDescription", b =>
                {
                    b.Property<int>("StackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stack_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StackId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("StackName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("stack_name");

                    b.HasKey("StackId")
                        .HasName("PK__tech_sta__A44AF929B7A3A9B6");

                    b.ToTable("tech_stack_description", (string)null);
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.TechStackSpec", b =>
                {
                    b.Property<int>("SpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("spec_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("ImgSrc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("img_src");

                    b.Property<int>("StackId")
                        .HasColumnType("int")
                        .HasColumnName("stack_id");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tool_name");

                    b.HasKey("SpecId")
                        .HasName("PK__tech_sta__F670C567B3B5AEFC");

                    b.HasIndex("StackId");

                    b.ToTable("tech_stack_spec", (string)null);
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("location");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.ExpProject", b =>
                {
                    b.HasOne("Portfolio_API.DataTypes.Models.Portfolio.Experience", "ExperiencedAtNavigation")
                        .WithMany("ExpProjects")
                        .HasForeignKey("ExperiencedAt")
                        .IsRequired()
                        .HasConstraintName("FK_ProjectTechStack_Experience");

                    b.HasOne("Portfolio_API.DataTypes.Models.Portfolio.Project", "Project")
                        .WithMany("ExpProjects")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_ProjectTechStack_Project");

                    b.HasOne("Portfolio_API.DataTypes.Models.Portfolio.TechStackSpec", "Techstack")
                        .WithMany("ExpProjects")
                        .HasForeignKey("TechstackId")
                        .IsRequired()
                        .HasConstraintName("FK_ProjectTechStack_TechStack");

                    b.Navigation("ExperiencedAtNavigation");

                    b.Navigation("Project");

                    b.Navigation("Techstack");
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.TechStackSpec", b =>
                {
                    b.HasOne("Portfolio_API.DataTypes.Models.Portfolio.TechStackDescription", "Stack")
                        .WithMany("TechStackSpecs")
                        .HasForeignKey("StackId")
                        .IsRequired()
                        .HasConstraintName("FK_stack_spec_description");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.Experience", b =>
                {
                    b.Navigation("ExpProjects");
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.Project", b =>
                {
                    b.Navigation("ExpProjects");
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.TechStackDescription", b =>
                {
                    b.Navigation("TechStackSpecs");
                });

            modelBuilder.Entity("Portfolio_API.DataTypes.Models.Portfolio.TechStackSpec", b =>
                {
                    b.Navigation("ExpProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
