// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio_API.DataAccess.Contexts;

#nullable disable

namespace Portfolio_API.DataAccess.Migrations.EmployeeDB
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20260308134113_CreateEmployeeDB")]
    partial class CreateEmployeeDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("Portfolio_API.Models.EmployeeManagementModels.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("attendance_id");

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("TEXT")
                        .HasColumnName("check_in");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("TEXT")
                        .HasColumnName("check_out");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("Portfolio_API.Models.EmployeeManagementModels.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("position");

                    b.HasKey("EmployeeId");

                    b.HasIndex(new[] { "Email" }, "IX_employees_email")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Portfolio_API.Models.EmployeeManagementModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex(new[] { "Username" }, "IX_users_username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Portfolio_API.Models.EmployeeManagementModels.Attendance", b =>
                {
                    b.HasOne("Portfolio_API.Models.EmployeeManagementModels.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Portfolio_API.Models.EmployeeManagementModels.User", b =>
                {
                    b.HasOne("Portfolio_API.Models.EmployeeManagementModels.Employee", "Employee")
                        .WithMany("Users")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Portfolio_API.Models.EmployeeManagementModels.Employee", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
